// 출처: 1등급 만들기 고등 미적분1 문제편 - Ⅰ.수열의 극한 > 01 수열의 극한 (p.8~12, 001~019번)
// concept: conceptSelect의 value와 매칭 / difficulty: diff-btn의 data-level과 매칭
// tier: "기본" | "기출유형" (책의 문제 3단계 코스 중 앞 두 단계에 해당)
const PROBLEMS = [
  { id: "001-1", concept: "limit", difficulty: "lower", tier: "기본",
    question: "다음 수열의 수렴과 발산을 조사하고, 수렴하면 그 극한값을 구하시오.\n{3 - 1/n}",
    answer: "3",
    explanation: "1/n → 0 이므로 3 - 1/n → 3. 수렴하고 극한값은 3이다." },
  { id: "001-2", concept: "limit", difficulty: "lower", tier: "기본",
    question: "다음 수열의 수렴과 발산을 조사하시오.\n{2n + 3}",
    answer: "발산",
    explanation: "n → ∞일 때 2n+3 → ∞이므로 양의 무한대로 발산한다." },
  { id: "001-3", concept: "limit", difficulty: "lower", tier: "기본",
    question: "다음 수열의 수렴과 발산을 조사하시오.\n{-2^(n-2)}",
    answer: "발산",
    explanation: "2^(n-2) → ∞이므로 -2^(n-2) → -∞. 음의 무한대로 발산한다." },
  { id: "001-4", concept: "limit", difficulty: "lower", tier: "기본",
    question: "다음 수열의 수렴과 발산을 조사하시오.\n{(-1)^n - 1}",
    answer: "발산",
    explanation: "n이 짝수면 0, 홀수면 -2를 반복하므로 한 값에 가까워지지 않는다. 진동하며 발산한다." },

  { id: "002-1", concept: "limit", difficulty: "lower", tier: "기본",
    question: "lim(n→∞) aₙ = -1, lim(n→∞) bₙ = 2일 때, 다음 극한값을 구하시오.\nlim(n→∞) (aₙ + bₙ)",
    answer: "1",
    explanation: "극한의 기본 성질에 의해 (-1) + 2 = 1." },
  { id: "002-2", concept: "limit", difficulty: "lower", tier: "기본",
    question: "lim(n→∞) aₙ = -1, lim(n→∞) bₙ = 2일 때, 다음 극한값을 구하시오.\nlim(n→∞) (2aₙ - bₙ)",
    answer: "-4",
    explanation: "2×(-1) - 2 = -4." },
  { id: "002-3", concept: "limit", difficulty: "lower", tier: "기본",
    question: "lim(n→∞) aₙ = -1, lim(n→∞) bₙ = 2일 때, 다음 극한값을 구하시오.\nlim(n→∞) 3aₙbₙ",
    answer: "-6",
    explanation: "3×(-1)×2 = -6." },
  { id: "002-4", concept: "limit", difficulty: "lower", tier: "기본",
    question: "lim(n→∞) aₙ = -1, lim(n→∞) bₙ = 2일 때, 다음 극한값을 구하시오.\nlim(n→∞) bₙ/(4aₙ)",
    answer: "-1/2",
    explanation: "2 / (4×(-1)) = 2/(-4) = -1/2." },

  { id: "003-1", concept: "limit", difficulty: "lower", tier: "기본",
    question: "다음 극한을 조사하시오.\nlim(n→∞) (n² - n)/(3n² + 2n + 1)",
    answer: "1/3",
    explanation: "분모의 최고차항 n²으로 분모, 분자를 나누면 (1-1/n)/(3+2/n+1/n²) → 1/3." },
  { id: "003-2", concept: "limit", difficulty: "lower", tier: "기본",
    question: "다음 극한을 조사하시오.\nlim(n→∞) (√(n²+1) - n)",
    answer: "0",
    explanation: "분자를 유리화하면 1/(√(n²+1)+n) → 0." },
  { id: "003-3", concept: "limit", difficulty: "lower", tier: "기본",
    question: "다음 극한을 조사하시오.\nlim(n→∞) (n² - 5n)",
    answer: "발산",
    explanation: "n²이 지배적이므로 n²-5n → ∞. 양의 무한대로 발산한다." },

  { id: "004", concept: "limit", difficulty: "lower", tier: "기본",
    question: "수열 {aₙ}이 모든 자연수 n에 대하여 부등식\n2n/(n+1) ≤ aₙ ≤ (2n+3)/(n+1)\n을 만족시킬 때, lim(n→∞) aₙ의 값을 구하시오.",
    answer: "2",
    explanation: "양 끝 수열이 모두 2로 수렴하므로 수열의 극한의 대소 관계(샌드위치 정리)에 의해 lim aₙ = 2." },

  { id: "005-1", concept: "limit", difficulty: "lower", tier: "기본",
    question: "다음 등비수열의 수렴과 발산을 조사하시오.\n{5ⁿ}",
    answer: "발산",
    explanation: "공비 r=5>1이므로 발산한다." },
  { id: "005-2", concept: "limit", difficulty: "lower", tier: "기본",
    question: "다음 등비수열의 수렴과 발산을 조사하시오.\n{2ⁿ/3ⁿ}",
    answer: "0",
    explanation: "{(2/3)ⁿ}이고 |r|=2/3<1이므로 0으로 수렴한다." },
  { id: "005-3", concept: "limit", difficulty: "lower", tier: "기본",
    question: "다음 등비수열의 수렴과 발산을 조사하시오.\n{(-1.5)ⁿ}",
    answer: "발산",
    explanation: "공비 r=-1.5로 r≤-1이므로 진동하며 발산한다." },
  { id: "005-4", concept: "limit", difficulty: "lower", tier: "기본",
    question: "다음 등비수열의 수렴과 발산을 조사하시오.\n{1/(√2)ⁿ}",
    answer: "0",
    explanation: "공비 r=1/√2이고 |r|<1이므로 0으로 수렴한다." },

  { id: "006-1", concept: "limit", difficulty: "lower", tier: "기본",
    question: "다음 등비수열이 수렴하기 위한 실수 r의 값의 범위를 구하시오.\n{(3r)ⁿ}",
    answer: "-1/3 < r ≤ 1/3",
    explanation: "등비수열이 수렴하려면 -1 < 공비 ≤ 1. 즉 -1 < 3r ≤ 1 이므로 -1/3 < r ≤ 1/3." },
  { id: "006-2", concept: "limit", difficulty: "lower", tier: "기본",
    question: "다음 등비수열이 수렴하기 위한 실수 r의 값의 범위를 구하시오.\n{(-r/5)ⁿ}",
    answer: "-5 ≤ r < 5",
    explanation: "-1 < -r/5 ≤ 1 의 각 변에 -5를 곱하면(부등호 방향이 바뀜) -5 ≤ r < 5." },

  { id: "007", concept: "limit", difficulty: "mid", tier: "기출유형",
    question: "다음 수열 중 수렴하는 것은?\n① 9-3n\n② (-1)ⁿ × n/(n+1)\n③ 2+(-1)ⁿ\n④ (√3)ⁿ\n⑤ (-1)ⁿ⁺¹ × 2/n",
    answer: "5",
    explanation: "①②③④는 모두 발산(무한대로 발산 또는 진동)한다. ⑤는 절댓값이 2/n→0으로 가면서 부호만 바뀌므로 0으로 수렴한다. 정답 ⑤." },
  { id: "008", concept: "limit", difficulty: "mid", tier: "기출유형",
    question: "발산하는 수열인 것만을 <보기>에서 있는 대로 고른 것은?\nㄱ. (2n+1)/n\nㄴ. (1-2n²)/n\nㄷ. 1/√n\nㄹ. cos(nπ)\n① ㄱ,ㄴ ② ㄱ,ㄷ ③ ㄴ,ㄷ ④ ㄴ,ㄹ ⑤ ㄷ,ㄹ",
    answer: "4",
    explanation: "ㄱ→2(수렴), ㄴ→-∞(발산), ㄷ→0(수렴), ㄹ=(-1)ⁿ(진동, 발산). 발산하는 것은 ㄴ,ㄹ이므로 정답 ④." },
  { id: "009", concept: "limit", difficulty: "mid", tier: "기출유형",
    question: "두 수열 {aₙ},{bₙ}에 대하여 lim(n→∞) aₙ=-3, lim(n→∞) bₙ=4일 때,\nlim(n→∞) (aₙ-2bₙ)/(3aₙ+bₙ)의 값을 구하시오.",
    answer: "11/5",
    explanation: "분자 → -3-8=-11, 분모 → -9+4=-5. (-11)/(-5) = 11/5." },
  { id: "010", concept: "limit", difficulty: "mid", tier: "기출유형",
    question: "수렴하는 두 수열 {aₙ},{bₙ}에 대하여 lim(n→∞)(aₙ+bₙ)=3, lim(n→∞) aₙbₙ=-4일 때, lim(n→∞)(aₙ²+bₙ²)의 값은?\n① 13 ② 14 ③ 15 ④ 16 ⑤ 17",
    answer: "17",
    explanation: "aₙ²+bₙ² = (aₙ+bₙ)² - 2aₙbₙ → 3² - 2×(-4) = 9+8 = 17. 정답 ⑤." },
  { id: "011", concept: "limit", difficulty: "mid", tier: "기출유형",
    question: "두 수열 {aₙ},{bₙ}에 대하여 aₙ=1/n-5, bₙ=2-1/(n-1)² 일 때, lim(n→∞) aₙ(2aₙ+7bₙ)의 값을 구하시오. (서술형)",
    answer: "-20",
    explanation: "aₙ→-5, bₙ→2. 2aₙ+7bₙ → -10+14=4. aₙ×4 → -5×4 = -20." },
  { id: "012", concept: "limit", difficulty: "mid", tier: "기출유형",
    question: "다음 중 옳지 않은 것은?\n① lim n²/(3n²+3n-1) = 1/3\n② lim (n+2)(2n-1)/(2n²+1) = 1\n③ lim 3n/√(n²+3n) = 3\n④ lim √n/(4n+1) = 1/4\n⑤ lim (√(n+2))/(√(n-1)+√(n+1)) = 1/2",
    answer: "4",
    explanation: "④ √n/(4n+1)은 분모·분자를 n으로 나누면 (1/√n)/(4+1/n) → 0/4 = 0 이지 1/4이 아니다. 나머지는 모두 옳다. 정답 ④." },
  { id: "013", concept: "limit", difficulty: "mid", tier: "기출유형",
    question: "lim(n→∞) n³/(1²+2²+3²+⋯+n²)의 값은?\n① 1 ② 2 ③ 3 ④ 4 ⑤ 5",
    answer: "3",
    explanation: "1²+⋯+n² = n(n+1)(2n+1)/6이므로 식은 6n³/[n(n+1)(2n+1)] = 6n²/[(n+1)(2n+1)] → 6/(1×2) = 3. 정답 ③." },
  { id: "014", concept: "limit", difficulty: "mid", tier: "기출유형",
    question: "lim(n→∞) {log₃(3n+1)+log₃(3n-1)-2log₃(n+3)}의 값은?\n① 1/2 ② 1 ③ 3/2 ④ 2 ⑤ 5/2",
    answer: "2",
    explanation: "로그를 합치면 log₃[(9n²-1)/(n²+6n+9)] → log₃9 = 2 (분수식이 9로 수렴). 정답 ④." },
  { id: "015", concept: "limit", difficulty: "mid", tier: "기출유형",
    question: "수열 {aₙ}의 첫째항부터 제n항까지의 합 Sₙ이 Sₙ=n²일 때, lim(n→∞) (2n+1)aₙ/(Sₙ+1)의 값은?\n① 2 ② 3 ③ 4 ④ 5 ⑤ 6",
    answer: "4",
    explanation: "aₙ=Sₙ-Sₙ₋₁=2n-1. 식은 (2n+1)(2n-1)/(n²+1)=(4n²-1)/(n²+1) → 4. 정답 ③." },
  { id: "016", concept: "limit", difficulty: "mid", tier: "기출유형",
    question: "자연수 n에 대하여 x에 대한 이차방정식\nx² - (5n-1)x + √(n²+1) + √(n²-1) = 0\n의 두 근을 aₙ, βₙ이라 할 때, lim(n→∞) (1/aₙ + 1/βₙ)의 값을 구하시오. (서술형)",
    answer: "5/2",
    explanation: "근과 계수의 관계로 aₙ+βₙ=5n-1, aₙβₙ=√(n²+1)+√(n²-1). 1/aₙ+1/βₙ=(aₙ+βₙ)/(aₙβₙ)=(5n-1)/(√(n²+1)+√(n²-1)) → 5/2 (분모는 2n에 가까워짐)." },
  { id: "017", concept: "limit", difficulty: "mid", tier: "기출유형",
    question: "lim(n→∞) √n(√(n+3)-√n)의 값은?\n① 0 ② 1/4 ③ 1/2 ④ 1 ⑤ 3/2",
    answer: "3/2",
    explanation: "√n(√(n+3)-√n) = 3√n/(√(n+3)+√n) → 3/(1+1) = 3/2. 정답 ⑤." },
  { id: "018", concept: "limit", difficulty: "mid", tier: "기출유형",
    question: "lim(n→∞) (√(n²+1000)-n)/(n-√(n²+999))의 값은?\n① -1000/999 ② -999/1000 ③ -489/1000 ④ 999/1000 ⑤ 1000/999",
    answer: "-1000/999",
    explanation: "분자 → 1000/(2n), 분모 → -999/(2n). 비율은 1000/(-999) = -1000/999. 정답 ①." },
  { id: "019", concept: "limit", difficulty: "mid", tier: "기출유형",
    question: "첫째항이 1이고 공차가 6인 등차수열 {aₙ}의 첫째항부터 제n항까지의 합을 Sₙ이라 할 때, lim(n→∞) (√(Sₙ₊₂)-√(Sₙ))의 값을 구하시오.",
    answer: "2√3",
    explanation: "Sₙ=3n²-2n. Sₙ₊₂-Sₙ=12n+8. 유리화하면 (12n+8)/(√Sₙ₊₂+√Sₙ) → 12/(2√3) = 2√3." },
];
